apply plugin: 'org.jetbrains.kotlin.multiplatform'

kotlin {
	sourceSets {
		commonMain {
			dependencies {
				implementation projects.mosaicTtyTerminal
				implementation libs.clikt
				implementation libs.finalizationHook
				implementation libs.kotlin.reflect
			}
		}
	}

	jvm {
		binaries {
			executable {
				mainClass = 'example.Main'
			}
		}
	}
}
