import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.NativeBuildType

apply plugin: 'org.jetbrains.kotlin.multiplatform'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply from: "$rootDir/addAllTargets.gradle"

kotlin {
	sourceSets {
		configureEach {
			languageSettings.optIn('kotlin.time.ExperimentalTime')
		}

		commonMain {
			dependencies {
				implementation projects.mosaicRuntime
				implementation 'org.jetbrains.kotlinx:kotlinx-datetime:0.7.1'
			}
		}
	}

	jvm {
		binaries {
			executable {
				mainClass = 'example.RrtopKt'
			}
		}
	}

	targets.withType(KotlinNativeTarget).configureEach { target ->
		target.binaries.executable {
			entryPoint = 'example.main'
			if (buildType == NativeBuildType.DEBUG) {
				linkTaskProvider.configure {
					enabled = false
				}
			}
		}
	}
}
