POM_ARTIFACT_ID=mosaic-tty
POM_NAME=Mosaic TTY

# By default, creating an additional Kotlin compilation and calling associateWith(mainCompilation)
# will produce a dependency on the jar task. We want to copy the output of the new compilation
# into the jar, though, so we need to disable this behavior to avoid a cyclic task dependency.
# See https://youtrack.jetbrains.com/issue/KT-78269
kotlin.build.archivesTaskOutputAsFriendModule=false
