// Generated by jextract

package com.jakewharton.mosaic.tty;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef __mbstate_t __darwin_mbstate_t
 * }
 */
public class __darwin_mbstate_t extends __mbstate_t {

    __darwin_mbstate_t() {
        // Should not be called directly
    }
}

