// Generated by jextract

package com.jakewharton.mosaic.tty;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _opaque_pthread_mutex_t {
 *     long __sig;
 *     char __opaque[56];
 * } __darwin_pthread_mutex_t
 * }
 */
public class __darwin_pthread_mutex_t extends _opaque_pthread_mutex_t {

    __darwin_pthread_mutex_t() {
        // Should not be called directly
    }
}

