// Generated by jextract

package com.jakewharton.mosaic.tty;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class Libmosaic {

    Libmosaic() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfLong C_LONG = ValueLayout.JAVA_LONG;
    private static final int true_ = (int)1L;
    /**
     * {@snippet lang=c :
     * #define true 1
     * }
     */
    public static int true_() {
        return true_;
    }
    private static final int false_ = (int)0L;
    /**
     * {@snippet lang=c :
     * #define false 0
     * }
     */
    public static int false_() {
        return false_;
    }
    private static final int __bool_true_false_are_defined = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __bool_true_false_are_defined 1
     * }
     */
    public static int __bool_true_false_are_defined() {
        return __bool_true_false_are_defined;
    }
    private static final int __WORDSIZE = (int)64L;
    /**
     * {@snippet lang=c :
     * #define __WORDSIZE 64
     * }
     */
    public static int __WORDSIZE() {
        return __WORDSIZE;
    }
    private static final int __has_safe_buffers = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __has_safe_buffers 0
     * }
     */
    public static int __has_safe_buffers() {
        return __has_safe_buffers;
    }
    private static final int __DARWIN_ONLY_64_BIT_INO_T = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_ONLY_64_BIT_INO_T 1
     * }
     */
    public static int __DARWIN_ONLY_64_BIT_INO_T() {
        return __DARWIN_ONLY_64_BIT_INO_T;
    }
    private static final int __DARWIN_ONLY_UNIX_CONFORMANCE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_ONLY_UNIX_CONFORMANCE 1
     * }
     */
    public static int __DARWIN_ONLY_UNIX_CONFORMANCE() {
        return __DARWIN_ONLY_UNIX_CONFORMANCE;
    }
    private static final int __DARWIN_ONLY_VERS_1050 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_ONLY_VERS_1050 1
     * }
     */
    public static int __DARWIN_ONLY_VERS_1050() {
        return __DARWIN_ONLY_VERS_1050;
    }
    private static final int __DARWIN_UNIX03 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_UNIX03 1
     * }
     */
    public static int __DARWIN_UNIX03() {
        return __DARWIN_UNIX03;
    }
    private static final int __DARWIN_64_BIT_INO_T = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_64_BIT_INO_T 1
     * }
     */
    public static int __DARWIN_64_BIT_INO_T() {
        return __DARWIN_64_BIT_INO_T;
    }
    private static final int __DARWIN_VERS_1050 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_VERS_1050 1
     * }
     */
    public static int __DARWIN_VERS_1050() {
        return __DARWIN_VERS_1050;
    }
    private static final int __DARWIN_NON_CANCELABLE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_NON_CANCELABLE 0
     * }
     */
    public static int __DARWIN_NON_CANCELABLE() {
        return __DARWIN_NON_CANCELABLE;
    }
    private static final int __STDC_WANT_LIB_EXT1__ = (int)1L;
    /**
     * {@snippet lang=c :
     * #define __STDC_WANT_LIB_EXT1__ 1
     * }
     */
    public static int __STDC_WANT_LIB_EXT1__() {
        return __STDC_WANT_LIB_EXT1__;
    }
    private static final int __DARWIN_NO_LONG_LONG = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_NO_LONG_LONG 0
     * }
     */
    public static int __DARWIN_NO_LONG_LONG() {
        return __DARWIN_NO_LONG_LONG;
    }
    private static final int _DARWIN_FEATURE_64_BIT_INODE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _DARWIN_FEATURE_64_BIT_INODE 1
     * }
     */
    public static int _DARWIN_FEATURE_64_BIT_INODE() {
        return _DARWIN_FEATURE_64_BIT_INODE;
    }
    private static final int _DARWIN_FEATURE_ONLY_64_BIT_INODE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _DARWIN_FEATURE_ONLY_64_BIT_INODE 1
     * }
     */
    public static int _DARWIN_FEATURE_ONLY_64_BIT_INODE() {
        return _DARWIN_FEATURE_ONLY_64_BIT_INODE;
    }
    private static final int _DARWIN_FEATURE_ONLY_VERS_1050 = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _DARWIN_FEATURE_ONLY_VERS_1050 1
     * }
     */
    public static int _DARWIN_FEATURE_ONLY_VERS_1050() {
        return _DARWIN_FEATURE_ONLY_VERS_1050;
    }
    private static final int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE 1
     * }
     */
    public static int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE() {
        return _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE;
    }
    private static final int _DARWIN_FEATURE_UNIX_CONFORMANCE = (int)3L;
    /**
     * {@snippet lang=c :
     * #define _DARWIN_FEATURE_UNIX_CONFORMANCE 3
     * }
     */
    public static int _DARWIN_FEATURE_UNIX_CONFORMANCE() {
        return _DARWIN_FEATURE_UNIX_CONFORMANCE;
    }
    private static final int __has_ptrcheck = (int)0L;
    /**
     * {@snippet lang=c :
     * #define __has_ptrcheck 0
     * }
     */
    public static int __has_ptrcheck() {
        return __has_ptrcheck;
    }
    private static final int USE_CLANG_TYPES = (int)0L;
    /**
     * {@snippet lang=c :
     * #define USE_CLANG_TYPES 0
     * }
     */
    public static int USE_CLANG_TYPES() {
        return USE_CLANG_TYPES;
    }
    private static final int __PTHREAD_SIZE__ = (int)8176L;
    /**
     * {@snippet lang=c :
     * #define __PTHREAD_SIZE__ 8176
     * }
     */
    public static int __PTHREAD_SIZE__() {
        return __PTHREAD_SIZE__;
    }
    private static final int __PTHREAD_ATTR_SIZE__ = (int)56L;
    /**
     * {@snippet lang=c :
     * #define __PTHREAD_ATTR_SIZE__ 56
     * }
     */
    public static int __PTHREAD_ATTR_SIZE__() {
        return __PTHREAD_ATTR_SIZE__;
    }
    private static final int __PTHREAD_MUTEXATTR_SIZE__ = (int)8L;
    /**
     * {@snippet lang=c :
     * #define __PTHREAD_MUTEXATTR_SIZE__ 8
     * }
     */
    public static int __PTHREAD_MUTEXATTR_SIZE__() {
        return __PTHREAD_MUTEXATTR_SIZE__;
    }
    private static final int __PTHREAD_MUTEX_SIZE__ = (int)56L;
    /**
     * {@snippet lang=c :
     * #define __PTHREAD_MUTEX_SIZE__ 56
     * }
     */
    public static int __PTHREAD_MUTEX_SIZE__() {
        return __PTHREAD_MUTEX_SIZE__;
    }
    private static final int __PTHREAD_CONDATTR_SIZE__ = (int)8L;
    /**
     * {@snippet lang=c :
     * #define __PTHREAD_CONDATTR_SIZE__ 8
     * }
     */
    public static int __PTHREAD_CONDATTR_SIZE__() {
        return __PTHREAD_CONDATTR_SIZE__;
    }
    private static final int __PTHREAD_COND_SIZE__ = (int)40L;
    /**
     * {@snippet lang=c :
     * #define __PTHREAD_COND_SIZE__ 40
     * }
     */
    public static int __PTHREAD_COND_SIZE__() {
        return __PTHREAD_COND_SIZE__;
    }
    private static final int __PTHREAD_ONCE_SIZE__ = (int)8L;
    /**
     * {@snippet lang=c :
     * #define __PTHREAD_ONCE_SIZE__ 8
     * }
     */
    public static int __PTHREAD_ONCE_SIZE__() {
        return __PTHREAD_ONCE_SIZE__;
    }
    private static final int __PTHREAD_RWLOCK_SIZE__ = (int)192L;
    /**
     * {@snippet lang=c :
     * #define __PTHREAD_RWLOCK_SIZE__ 192
     * }
     */
    public static int __PTHREAD_RWLOCK_SIZE__() {
        return __PTHREAD_RWLOCK_SIZE__;
    }
    private static final int __PTHREAD_RWLOCKATTR_SIZE__ = (int)16L;
    /**
     * {@snippet lang=c :
     * #define __PTHREAD_RWLOCKATTR_SIZE__ 16
     * }
     */
    public static int __PTHREAD_RWLOCKATTR_SIZE__() {
        return __PTHREAD_RWLOCKATTR_SIZE__;
    }
    private static final int INT8_MAX = (int)127L;
    /**
     * {@snippet lang=c :
     * #define INT8_MAX 127
     * }
     */
    public static int INT8_MAX() {
        return INT8_MAX;
    }
    private static final int INT16_MAX = (int)32767L;
    /**
     * {@snippet lang=c :
     * #define INT16_MAX 32767
     * }
     */
    public static int INT16_MAX() {
        return INT16_MAX;
    }
    private static final int INT32_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define INT32_MAX 2147483647
     * }
     */
    public static int INT32_MAX() {
        return INT32_MAX;
    }
    private static final int UINT8_MAX = (int)255L;
    /**
     * {@snippet lang=c :
     * #define UINT8_MAX 255
     * }
     */
    public static int UINT8_MAX() {
        return UINT8_MAX;
    }
    private static final int UINT16_MAX = (int)65535L;
    /**
     * {@snippet lang=c :
     * #define UINT16_MAX 65535
     * }
     */
    public static int UINT16_MAX() {
        return UINT16_MAX;
    }
    /**
     * {@snippet lang=c :
     * typedef signed char int8_t
     * }
     */
    public static final OfByte int8_t = Libmosaic.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef short int16_t
     * }
     */
    public static final OfShort int16_t = Libmosaic.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef int int32_t
     * }
     */
    public static final OfInt int32_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef long long int64_t
     * }
     */
    public static final OfLong int64_t = Libmosaic.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned char uint8_t
     * }
     */
    public static final OfByte uint8_t = Libmosaic.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef unsigned short uint16_t
     * }
     */
    public static final OfShort uint16_t = Libmosaic.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int uint32_t
     * }
     */
    public static final OfInt uint32_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned long long uint64_t
     * }
     */
    public static final OfLong uint64_t = Libmosaic.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef int8_t int_least8_t
     * }
     */
    public static final OfByte int_least8_t = Libmosaic.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef int16_t int_least16_t
     * }
     */
    public static final OfShort int_least16_t = Libmosaic.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef int32_t int_least32_t
     * }
     */
    public static final OfInt int_least32_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int64_t int_least64_t
     * }
     */
    public static final OfLong int_least64_t = Libmosaic.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef uint8_t uint_least8_t
     * }
     */
    public static final OfByte uint_least8_t = Libmosaic.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef uint16_t uint_least16_t
     * }
     */
    public static final OfShort uint_least16_t = Libmosaic.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef uint32_t uint_least32_t
     * }
     */
    public static final OfInt uint_least32_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef uint64_t uint_least64_t
     * }
     */
    public static final OfLong uint_least64_t = Libmosaic.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef int8_t int_fast8_t
     * }
     */
    public static final OfByte int_fast8_t = Libmosaic.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef int16_t int_fast16_t
     * }
     */
    public static final OfShort int_fast16_t = Libmosaic.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef int32_t int_fast32_t
     * }
     */
    public static final OfInt int_fast32_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int64_t int_fast64_t
     * }
     */
    public static final OfLong int_fast64_t = Libmosaic.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef uint8_t uint_fast8_t
     * }
     */
    public static final OfByte uint_fast8_t = Libmosaic.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef uint16_t uint_fast16_t
     * }
     */
    public static final OfShort uint_fast16_t = Libmosaic.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef uint32_t uint_fast32_t
     * }
     */
    public static final OfInt uint_fast32_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef uint64_t uint_fast64_t
     * }
     */
    public static final OfLong uint_fast64_t = Libmosaic.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef signed char __int8_t
     * }
     */
    public static final OfByte __int8_t = Libmosaic.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef unsigned char __uint8_t
     * }
     */
    public static final OfByte __uint8_t = Libmosaic.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef short __int16_t
     * }
     */
    public static final OfShort __int16_t = Libmosaic.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef unsigned short __uint16_t
     * }
     */
    public static final OfShort __uint16_t = Libmosaic.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef int __int32_t
     * }
     */
    public static final OfInt __int32_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __uint32_t
     * }
     */
    public static final OfInt __uint32_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef long long __int64_t
     * }
     */
    public static final OfLong __int64_t = Libmosaic.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long long __uint64_t
     * }
     */
    public static final OfLong __uint64_t = Libmosaic.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef long __darwin_intptr_t
     * }
     */
    public static final OfLong __darwin_intptr_t = Libmosaic.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __darwin_natural_t
     * }
     */
    public static final OfInt __darwin_natural_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int __darwin_ct_rune_t
     * }
     */
    public static final OfInt __darwin_ct_rune_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef long __darwin_ptrdiff_t
     * }
     */
    public static final OfLong __darwin_ptrdiff_t = Libmosaic.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __darwin_size_t
     * }
     */
    public static final OfLong __darwin_size_t = Libmosaic.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __builtin_va_list __darwin_va_list
     * }
     */
    public static final AddressLayout __darwin_va_list = Libmosaic.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef int __darwin_wchar_t
     * }
     */
    public static final OfInt __darwin_wchar_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __darwin_wchar_t __darwin_rune_t
     * }
     */
    public static final OfInt __darwin_rune_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int __darwin_wint_t
     * }
     */
    public static final OfInt __darwin_wint_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __darwin_clock_t
     * }
     */
    public static final OfLong __darwin_clock_t = Libmosaic.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __uint32_t __darwin_socklen_t
     * }
     */
    public static final OfInt __darwin_socklen_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef long __darwin_ssize_t
     * }
     */
    public static final OfLong __darwin_ssize_t = Libmosaic.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long __darwin_time_t
     * }
     */
    public static final OfLong __darwin_time_t = Libmosaic.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __int64_t __darwin_blkcnt_t
     * }
     */
    public static final OfLong __darwin_blkcnt_t = Libmosaic.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef __int32_t __darwin_blksize_t
     * }
     */
    public static final OfInt __darwin_blksize_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __int32_t __darwin_dev_t
     * }
     */
    public static final OfInt __darwin_dev_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __darwin_fsblkcnt_t
     * }
     */
    public static final OfInt __darwin_fsblkcnt_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __darwin_fsfilcnt_t
     * }
     */
    public static final OfInt __darwin_fsfilcnt_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __uint32_t __darwin_gid_t
     * }
     */
    public static final OfInt __darwin_gid_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __uint32_t __darwin_id_t
     * }
     */
    public static final OfInt __darwin_id_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __uint64_t __darwin_ino64_t
     * }
     */
    public static final OfLong __darwin_ino64_t = Libmosaic.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef __darwin_ino64_t __darwin_ino_t
     * }
     */
    public static final OfLong __darwin_ino_t = Libmosaic.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef __darwin_natural_t __darwin_mach_port_name_t
     * }
     */
    public static final OfInt __darwin_mach_port_name_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __darwin_mach_port_name_t __darwin_mach_port_t
     * }
     */
    public static final OfInt __darwin_mach_port_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __uint16_t __darwin_mode_t
     * }
     */
    public static final OfShort __darwin_mode_t = Libmosaic.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef __int64_t __darwin_off_t
     * }
     */
    public static final OfLong __darwin_off_t = Libmosaic.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef __int32_t __darwin_pid_t
     * }
     */
    public static final OfInt __darwin_pid_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __uint32_t __darwin_sigset_t
     * }
     */
    public static final OfInt __darwin_sigset_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __int32_t __darwin_suseconds_t
     * }
     */
    public static final OfInt __darwin_suseconds_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __uint32_t __darwin_uid_t
     * }
     */
    public static final OfInt __darwin_uid_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __uint32_t __darwin_useconds_t
     * }
     */
    public static final OfInt __darwin_useconds_t = Libmosaic.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __darwin_pthread_key_t
     * }
     */
    public static final OfLong __darwin_pthread_key_t = Libmosaic.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef struct _opaque_pthread_t {
     *     long __sig;
     *     struct __darwin_pthread_handler_rec *__cleanup_stack;
     *     char __opaque[8176];
     * } *__darwin_pthread_t
     * }
     */
    public static final AddressLayout __darwin_pthread_t = Libmosaic.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef __darwin_intptr_t intptr_t
     * }
     */
    public static final OfLong intptr_t = Libmosaic.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long uintptr_t
     * }
     */
    public static final OfLong uintptr_t = Libmosaic.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long intmax_t
     * }
     */
    public static final OfLong intmax_t = Libmosaic.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long uintmax_t
     * }
     */
    public static final OfLong uintmax_t = Libmosaic.C_LONG;

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * MosaicTtyInitResult tty_init()
     * }
     */
    public static class tty_init {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                MosaicTtyInitResult.layout()        );
        private static final MemorySegment ADDR = Libmosaic.findOrThrow("tty_init");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private tty_init(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * MosaicTtyInitResult tty_init()
         * }
         */
        public static tty_init makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new tty_init(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public MemorySegment apply(SegmentAllocator allocator, Object... x0) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("tty_init", allocator, x0);
                }
                return (MemorySegment) spreader.invokeExact(allocator, x0);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static class tty_setCallback {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Libmosaic.C_POINTER,
            Libmosaic.C_POINTER
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("tty_setCallback");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void tty_setCallback(MosaicTty *tty, MosaicTtyCallback *callback)
     * }
     */
    public static FunctionDescriptor tty_setCallback$descriptor() {
        return tty_setCallback.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void tty_setCallback(MosaicTty *tty, MosaicTtyCallback *callback)
     * }
     */
    public static MethodHandle tty_setCallback$handle() {
        return tty_setCallback.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void tty_setCallback(MosaicTty *tty, MosaicTtyCallback *callback)
     * }
     */
    public static MemorySegment tty_setCallback$address() {
        return tty_setCallback.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void tty_setCallback(MosaicTty *tty, MosaicTtyCallback *callback)
     * }
     */
    public static void tty_setCallback(MemorySegment tty, MemorySegment callback) {
        var mh$ = tty_setCallback.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tty_setCallback", tty, callback);
            }
            mh$.invokeExact(tty, callback);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tty_read {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            MosaicTtyIoResult.layout(),
            Libmosaic.C_POINTER,
            Libmosaic.C_POINTER,
            Libmosaic.C_INT
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("tty_read");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * MosaicTtyIoResult tty_read(MosaicTty *tty, uint8_t *buffer, int count)
     * }
     */
    public static FunctionDescriptor tty_read$descriptor() {
        return tty_read.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * MosaicTtyIoResult tty_read(MosaicTty *tty, uint8_t *buffer, int count)
     * }
     */
    public static MethodHandle tty_read$handle() {
        return tty_read.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * MosaicTtyIoResult tty_read(MosaicTty *tty, uint8_t *buffer, int count)
     * }
     */
    public static MemorySegment tty_read$address() {
        return tty_read.ADDR;
    }

    /**
     * {@snippet lang=c :
     * MosaicTtyIoResult tty_read(MosaicTty *tty, uint8_t *buffer, int count)
     * }
     */
    public static MemorySegment tty_read(SegmentAllocator allocator, MemorySegment tty, MemorySegment buffer, int count) {
        var mh$ = tty_read.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tty_read", allocator, tty, buffer, count);
            }
            return (MemorySegment)mh$.invokeExact(allocator, tty, buffer, count);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tty_readWithTimeout {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            MosaicTtyIoResult.layout(),
            Libmosaic.C_POINTER,
            Libmosaic.C_POINTER,
            Libmosaic.C_INT,
            Libmosaic.C_INT
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("tty_readWithTimeout");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * MosaicTtyIoResult tty_readWithTimeout(MosaicTty *tty, uint8_t *buffer, int count, int timeoutMillis)
     * }
     */
    public static FunctionDescriptor tty_readWithTimeout$descriptor() {
        return tty_readWithTimeout.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * MosaicTtyIoResult tty_readWithTimeout(MosaicTty *tty, uint8_t *buffer, int count, int timeoutMillis)
     * }
     */
    public static MethodHandle tty_readWithTimeout$handle() {
        return tty_readWithTimeout.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * MosaicTtyIoResult tty_readWithTimeout(MosaicTty *tty, uint8_t *buffer, int count, int timeoutMillis)
     * }
     */
    public static MemorySegment tty_readWithTimeout$address() {
        return tty_readWithTimeout.ADDR;
    }

    /**
     * {@snippet lang=c :
     * MosaicTtyIoResult tty_readWithTimeout(MosaicTty *tty, uint8_t *buffer, int count, int timeoutMillis)
     * }
     */
    public static MemorySegment tty_readWithTimeout(SegmentAllocator allocator, MemorySegment tty, MemorySegment buffer, int count, int timeoutMillis) {
        var mh$ = tty_readWithTimeout.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tty_readWithTimeout", allocator, tty, buffer, count, timeoutMillis);
            }
            return (MemorySegment)mh$.invokeExact(allocator, tty, buffer, count, timeoutMillis);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tty_interruptRead {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Libmosaic.C_INT,
            Libmosaic.C_POINTER
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("tty_interruptRead");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t tty_interruptRead(MosaicTty *tty)
     * }
     */
    public static FunctionDescriptor tty_interruptRead$descriptor() {
        return tty_interruptRead.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t tty_interruptRead(MosaicTty *tty)
     * }
     */
    public static MethodHandle tty_interruptRead$handle() {
        return tty_interruptRead.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t tty_interruptRead(MosaicTty *tty)
     * }
     */
    public static MemorySegment tty_interruptRead$address() {
        return tty_interruptRead.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t tty_interruptRead(MosaicTty *tty)
     * }
     */
    public static int tty_interruptRead(MemorySegment tty) {
        var mh$ = tty_interruptRead.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tty_interruptRead", tty);
            }
            return (int)mh$.invokeExact(tty);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tty_write {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            MosaicTtyIoResult.layout(),
            Libmosaic.C_POINTER,
            Libmosaic.C_POINTER,
            Libmosaic.C_INT
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("tty_write");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * MosaicTtyIoResult tty_write(MosaicTty *tty, uint8_t *buffer, int count)
     * }
     */
    public static FunctionDescriptor tty_write$descriptor() {
        return tty_write.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * MosaicTtyIoResult tty_write(MosaicTty *tty, uint8_t *buffer, int count)
     * }
     */
    public static MethodHandle tty_write$handle() {
        return tty_write.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * MosaicTtyIoResult tty_write(MosaicTty *tty, uint8_t *buffer, int count)
     * }
     */
    public static MemorySegment tty_write$address() {
        return tty_write.ADDR;
    }

    /**
     * {@snippet lang=c :
     * MosaicTtyIoResult tty_write(MosaicTty *tty, uint8_t *buffer, int count)
     * }
     */
    public static MemorySegment tty_write(SegmentAllocator allocator, MemorySegment tty, MemorySegment buffer, int count) {
        var mh$ = tty_write.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tty_write", allocator, tty, buffer, count);
            }
            return (MemorySegment)mh$.invokeExact(allocator, tty, buffer, count);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tty_enableRawMode {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Libmosaic.C_INT,
            Libmosaic.C_POINTER
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("tty_enableRawMode");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t tty_enableRawMode(MosaicTty *tty)
     * }
     */
    public static FunctionDescriptor tty_enableRawMode$descriptor() {
        return tty_enableRawMode.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t tty_enableRawMode(MosaicTty *tty)
     * }
     */
    public static MethodHandle tty_enableRawMode$handle() {
        return tty_enableRawMode.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t tty_enableRawMode(MosaicTty *tty)
     * }
     */
    public static MemorySegment tty_enableRawMode$address() {
        return tty_enableRawMode.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t tty_enableRawMode(MosaicTty *tty)
     * }
     */
    public static int tty_enableRawMode(MemorySegment tty) {
        var mh$ = tty_enableRawMode.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tty_enableRawMode", tty);
            }
            return (int)mh$.invokeExact(tty);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tty_enableWindowResizeEvents {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Libmosaic.C_INT,
            Libmosaic.C_POINTER
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("tty_enableWindowResizeEvents");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t tty_enableWindowResizeEvents(MosaicTty *tty)
     * }
     */
    public static FunctionDescriptor tty_enableWindowResizeEvents$descriptor() {
        return tty_enableWindowResizeEvents.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t tty_enableWindowResizeEvents(MosaicTty *tty)
     * }
     */
    public static MethodHandle tty_enableWindowResizeEvents$handle() {
        return tty_enableWindowResizeEvents.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t tty_enableWindowResizeEvents(MosaicTty *tty)
     * }
     */
    public static MemorySegment tty_enableWindowResizeEvents$address() {
        return tty_enableWindowResizeEvents.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t tty_enableWindowResizeEvents(MosaicTty *tty)
     * }
     */
    public static int tty_enableWindowResizeEvents(MemorySegment tty) {
        var mh$ = tty_enableWindowResizeEvents.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tty_enableWindowResizeEvents", tty);
            }
            return (int)mh$.invokeExact(tty);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tty_currentTerminalSize {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            MosaicTtyTerminalSizeResult.layout(),
            Libmosaic.C_POINTER
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("tty_currentTerminalSize");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * MosaicTtyTerminalSizeResult tty_currentTerminalSize(MosaicTty *tty)
     * }
     */
    public static FunctionDescriptor tty_currentTerminalSize$descriptor() {
        return tty_currentTerminalSize.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * MosaicTtyTerminalSizeResult tty_currentTerminalSize(MosaicTty *tty)
     * }
     */
    public static MethodHandle tty_currentTerminalSize$handle() {
        return tty_currentTerminalSize.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * MosaicTtyTerminalSizeResult tty_currentTerminalSize(MosaicTty *tty)
     * }
     */
    public static MemorySegment tty_currentTerminalSize$address() {
        return tty_currentTerminalSize.ADDR;
    }

    /**
     * {@snippet lang=c :
     * MosaicTtyTerminalSizeResult tty_currentTerminalSize(MosaicTty *tty)
     * }
     */
    public static MemorySegment tty_currentTerminalSize(SegmentAllocator allocator, MemorySegment tty) {
        var mh$ = tty_currentTerminalSize.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tty_currentTerminalSize", allocator, tty);
            }
            return (MemorySegment)mh$.invokeExact(allocator, tty);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tty_reset {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Libmosaic.C_INT,
            Libmosaic.C_POINTER
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("tty_reset");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t tty_reset(MosaicTty *tty)
     * }
     */
    public static FunctionDescriptor tty_reset$descriptor() {
        return tty_reset.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t tty_reset(MosaicTty *tty)
     * }
     */
    public static MethodHandle tty_reset$handle() {
        return tty_reset.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t tty_reset(MosaicTty *tty)
     * }
     */
    public static MemorySegment tty_reset$address() {
        return tty_reset.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t tty_reset(MosaicTty *tty)
     * }
     */
    public static int tty_reset(MemorySegment tty) {
        var mh$ = tty_reset.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tty_reset", tty);
            }
            return (int)mh$.invokeExact(tty);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tty_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Libmosaic.C_INT,
            Libmosaic.C_POINTER
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("tty_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t tty_free(MosaicTty *tty)
     * }
     */
    public static FunctionDescriptor tty_free$descriptor() {
        return tty_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t tty_free(MosaicTty *tty)
     * }
     */
    public static MethodHandle tty_free$handle() {
        return tty_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t tty_free(MosaicTty *tty)
     * }
     */
    public static MemorySegment tty_free$address() {
        return tty_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t tty_free(MosaicTty *tty)
     * }
     */
    public static int tty_free(MemorySegment tty) {
        var mh$ = tty_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tty_free", tty);
            }
            return (int)mh$.invokeExact(tty);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * MosaicTestTtyInitResult testTty_init()
     * }
     */
    public static class testTty_init {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                MosaicTestTtyInitResult.layout()        );
        private static final MemorySegment ADDR = Libmosaic.findOrThrow("testTty_init");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private testTty_init(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * MosaicTestTtyInitResult testTty_init()
         * }
         */
        public static testTty_init makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new testTty_init(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public MemorySegment apply(SegmentAllocator allocator, Object... x0) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("testTty_init", allocator, x0);
                }
                return (MemorySegment) spreader.invokeExact(allocator, x0);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static class testTty_getTty {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Libmosaic.C_POINTER,
            Libmosaic.C_POINTER
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("testTty_getTty");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * MosaicTty *testTty_getTty(MosaicTestTty *testTty)
     * }
     */
    public static FunctionDescriptor testTty_getTty$descriptor() {
        return testTty_getTty.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * MosaicTty *testTty_getTty(MosaicTestTty *testTty)
     * }
     */
    public static MethodHandle testTty_getTty$handle() {
        return testTty_getTty.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * MosaicTty *testTty_getTty(MosaicTestTty *testTty)
     * }
     */
    public static MemorySegment testTty_getTty$address() {
        return testTty_getTty.ADDR;
    }

    /**
     * {@snippet lang=c :
     * MosaicTty *testTty_getTty(MosaicTestTty *testTty)
     * }
     */
    public static MemorySegment testTty_getTty(MemorySegment testTty) {
        var mh$ = testTty_getTty.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("testTty_getTty", testTty);
            }
            return (MemorySegment)mh$.invokeExact(testTty);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class testTty_write {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            MosaicTtyIoResult.layout(),
            Libmosaic.C_POINTER,
            Libmosaic.C_POINTER,
            Libmosaic.C_INT
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("testTty_write");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * MosaicTtyIoResult testTty_write(MosaicTestTty *testTty, uint8_t *buffer, int count)
     * }
     */
    public static FunctionDescriptor testTty_write$descriptor() {
        return testTty_write.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * MosaicTtyIoResult testTty_write(MosaicTestTty *testTty, uint8_t *buffer, int count)
     * }
     */
    public static MethodHandle testTty_write$handle() {
        return testTty_write.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * MosaicTtyIoResult testTty_write(MosaicTestTty *testTty, uint8_t *buffer, int count)
     * }
     */
    public static MemorySegment testTty_write$address() {
        return testTty_write.ADDR;
    }

    /**
     * {@snippet lang=c :
     * MosaicTtyIoResult testTty_write(MosaicTestTty *testTty, uint8_t *buffer, int count)
     * }
     */
    public static MemorySegment testTty_write(SegmentAllocator allocator, MemorySegment testTty, MemorySegment buffer, int count) {
        var mh$ = testTty_write.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("testTty_write", allocator, testTty, buffer, count);
            }
            return (MemorySegment)mh$.invokeExact(allocator, testTty, buffer, count);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class testTty_read {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            MosaicTtyIoResult.layout(),
            Libmosaic.C_POINTER,
            Libmosaic.C_POINTER,
            Libmosaic.C_INT
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("testTty_read");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * MosaicTtyIoResult testTty_read(MosaicTestTty *testTty, uint8_t *buffer, int count)
     * }
     */
    public static FunctionDescriptor testTty_read$descriptor() {
        return testTty_read.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * MosaicTtyIoResult testTty_read(MosaicTestTty *testTty, uint8_t *buffer, int count)
     * }
     */
    public static MethodHandle testTty_read$handle() {
        return testTty_read.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * MosaicTtyIoResult testTty_read(MosaicTestTty *testTty, uint8_t *buffer, int count)
     * }
     */
    public static MemorySegment testTty_read$address() {
        return testTty_read.ADDR;
    }

    /**
     * {@snippet lang=c :
     * MosaicTtyIoResult testTty_read(MosaicTestTty *testTty, uint8_t *buffer, int count)
     * }
     */
    public static MemorySegment testTty_read(SegmentAllocator allocator, MemorySegment testTty, MemorySegment buffer, int count) {
        var mh$ = testTty_read.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("testTty_read", allocator, testTty, buffer, count);
            }
            return (MemorySegment)mh$.invokeExact(allocator, testTty, buffer, count);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class testTty_interruptRead {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Libmosaic.C_INT,
            Libmosaic.C_POINTER
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("testTty_interruptRead");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t testTty_interruptRead(MosaicTestTty *testTty)
     * }
     */
    public static FunctionDescriptor testTty_interruptRead$descriptor() {
        return testTty_interruptRead.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t testTty_interruptRead(MosaicTestTty *testTty)
     * }
     */
    public static MethodHandle testTty_interruptRead$handle() {
        return testTty_interruptRead.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t testTty_interruptRead(MosaicTestTty *testTty)
     * }
     */
    public static MemorySegment testTty_interruptRead$address() {
        return testTty_interruptRead.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t testTty_interruptRead(MosaicTestTty *testTty)
     * }
     */
    public static int testTty_interruptRead(MemorySegment testTty) {
        var mh$ = testTty_interruptRead.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("testTty_interruptRead", testTty);
            }
            return (int)mh$.invokeExact(testTty);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class testTty_resize {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Libmosaic.C_INT,
            Libmosaic.C_POINTER,
            Libmosaic.C_INT,
            Libmosaic.C_INT,
            Libmosaic.C_INT,
            Libmosaic.C_INT
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("testTty_resize");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t testTty_resize(MosaicTestTty *testTty, int columns, int rows, int width, int height)
     * }
     */
    public static FunctionDescriptor testTty_resize$descriptor() {
        return testTty_resize.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t testTty_resize(MosaicTestTty *testTty, int columns, int rows, int width, int height)
     * }
     */
    public static MethodHandle testTty_resize$handle() {
        return testTty_resize.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t testTty_resize(MosaicTestTty *testTty, int columns, int rows, int width, int height)
     * }
     */
    public static MemorySegment testTty_resize$address() {
        return testTty_resize.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t testTty_resize(MosaicTestTty *testTty, int columns, int rows, int width, int height)
     * }
     */
    public static int testTty_resize(MemorySegment testTty, int columns, int rows, int width, int height) {
        var mh$ = testTty_resize.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("testTty_resize", testTty, columns, rows, width, height);
            }
            return (int)mh$.invokeExact(testTty, columns, rows, width, height);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class testTty_sendFocusEvent {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Libmosaic.C_INT,
            Libmosaic.C_POINTER,
            Libmosaic.C_BOOL
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("testTty_sendFocusEvent");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t testTty_sendFocusEvent(MosaicTestTty *testTty, bool focused)
     * }
     */
    public static FunctionDescriptor testTty_sendFocusEvent$descriptor() {
        return testTty_sendFocusEvent.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t testTty_sendFocusEvent(MosaicTestTty *testTty, bool focused)
     * }
     */
    public static MethodHandle testTty_sendFocusEvent$handle() {
        return testTty_sendFocusEvent.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t testTty_sendFocusEvent(MosaicTestTty *testTty, bool focused)
     * }
     */
    public static MemorySegment testTty_sendFocusEvent$address() {
        return testTty_sendFocusEvent.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t testTty_sendFocusEvent(MosaicTestTty *testTty, bool focused)
     * }
     */
    public static int testTty_sendFocusEvent(MemorySegment testTty, boolean focused) {
        var mh$ = testTty_sendFocusEvent.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("testTty_sendFocusEvent", testTty, focused);
            }
            return (int)mh$.invokeExact(testTty, focused);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class testTty_sendKeyEvent {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Libmosaic.C_INT,
            Libmosaic.C_POINTER
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("testTty_sendKeyEvent");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t testTty_sendKeyEvent(MosaicTestTty *testTty)
     * }
     */
    public static FunctionDescriptor testTty_sendKeyEvent$descriptor() {
        return testTty_sendKeyEvent.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t testTty_sendKeyEvent(MosaicTestTty *testTty)
     * }
     */
    public static MethodHandle testTty_sendKeyEvent$handle() {
        return testTty_sendKeyEvent.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t testTty_sendKeyEvent(MosaicTestTty *testTty)
     * }
     */
    public static MemorySegment testTty_sendKeyEvent$address() {
        return testTty_sendKeyEvent.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t testTty_sendKeyEvent(MosaicTestTty *testTty)
     * }
     */
    public static int testTty_sendKeyEvent(MemorySegment testTty) {
        var mh$ = testTty_sendKeyEvent.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("testTty_sendKeyEvent", testTty);
            }
            return (int)mh$.invokeExact(testTty);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class testTty_sendMouseEvent {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Libmosaic.C_INT,
            Libmosaic.C_POINTER
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("testTty_sendMouseEvent");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t testTty_sendMouseEvent(MosaicTestTty *testTty)
     * }
     */
    public static FunctionDescriptor testTty_sendMouseEvent$descriptor() {
        return testTty_sendMouseEvent.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t testTty_sendMouseEvent(MosaicTestTty *testTty)
     * }
     */
    public static MethodHandle testTty_sendMouseEvent$handle() {
        return testTty_sendMouseEvent.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t testTty_sendMouseEvent(MosaicTestTty *testTty)
     * }
     */
    public static MemorySegment testTty_sendMouseEvent$address() {
        return testTty_sendMouseEvent.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t testTty_sendMouseEvent(MosaicTestTty *testTty)
     * }
     */
    public static int testTty_sendMouseEvent(MemorySegment testTty) {
        var mh$ = testTty_sendMouseEvent.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("testTty_sendMouseEvent", testTty);
            }
            return (int)mh$.invokeExact(testTty);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class testTty_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Libmosaic.C_INT,
            Libmosaic.C_POINTER
        );

        public static final MemorySegment ADDR = Libmosaic.findOrThrow("testTty_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t testTty_free(MosaicTestTty *testTty)
     * }
     */
    public static FunctionDescriptor testTty_free$descriptor() {
        return testTty_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t testTty_free(MosaicTestTty *testTty)
     * }
     */
    public static MethodHandle testTty_free$handle() {
        return testTty_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t testTty_free(MosaicTestTty *testTty)
     * }
     */
    public static MemorySegment testTty_free$address() {
        return testTty_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t testTty_free(MosaicTestTty *testTty)
     * }
     */
    public static int testTty_free(MemorySegment testTty) {
        var mh$ = testTty_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("testTty_free", testTty);
            }
            return (int)mh$.invokeExact(testTty);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    /**
     * {@snippet lang=c :
     * #define __DARWIN_SUF_EXTSN "$DARWIN_EXTSN"
     * }
     */
    public static MemorySegment __DARWIN_SUF_EXTSN() {
        class Holder {
            static final MemorySegment __DARWIN_SUF_EXTSN
                = Libmosaic.LIBRARY_ARENA.allocateFrom("$DARWIN_EXTSN");
        }
        return Holder.__DARWIN_SUF_EXTSN;
    }
    private static final long __DARWIN_C_ANSI = 4096L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_C_ANSI 4096
     * }
     */
    public static long __DARWIN_C_ANSI() {
        return __DARWIN_C_ANSI;
    }
    private static final long __DARWIN_C_FULL = 900000L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_C_FULL 900000
     * }
     */
    public static long __DARWIN_C_FULL() {
        return __DARWIN_C_FULL;
    }
    private static final long __DARWIN_C_LEVEL = 900000L;
    /**
     * {@snippet lang=c :
     * #define __DARWIN_C_LEVEL 900000
     * }
     */
    public static long __DARWIN_C_LEVEL() {
        return __DARWIN_C_LEVEL;
    }
    private static final MemorySegment __DARWIN_NULL = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define __DARWIN_NULL (void*) 0
     * }
     */
    public static MemorySegment __DARWIN_NULL() {
        return __DARWIN_NULL;
    }
    private static final long INT64_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INT64_MAX 9223372036854775807
     * }
     */
    public static long INT64_MAX() {
        return INT64_MAX;
    }
    private static final int INT8_MIN = (int)-128L;
    /**
     * {@snippet lang=c :
     * #define INT8_MIN -128
     * }
     */
    public static int INT8_MIN() {
        return INT8_MIN;
    }
    private static final int INT16_MIN = (int)-32768L;
    /**
     * {@snippet lang=c :
     * #define INT16_MIN -32768
     * }
     */
    public static int INT16_MIN() {
        return INT16_MIN;
    }
    private static final int INT32_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define INT32_MIN -2147483648
     * }
     */
    public static int INT32_MIN() {
        return INT32_MIN;
    }
    private static final long INT64_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INT64_MIN -9223372036854775808
     * }
     */
    public static long INT64_MIN() {
        return INT64_MIN;
    }
    private static final int UINT32_MAX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define UINT32_MAX 4294967295
     * }
     */
    public static int UINT32_MAX() {
        return UINT32_MAX;
    }
    private static final long UINT64_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINT64_MAX -1
     * }
     */
    public static long UINT64_MAX() {
        return UINT64_MAX;
    }
    private static final int INT_LEAST8_MIN = (int)-128L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST8_MIN -128
     * }
     */
    public static int INT_LEAST8_MIN() {
        return INT_LEAST8_MIN;
    }
    private static final int INT_LEAST16_MIN = (int)-32768L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST16_MIN -32768
     * }
     */
    public static int INT_LEAST16_MIN() {
        return INT_LEAST16_MIN;
    }
    private static final int INT_LEAST32_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST32_MIN -2147483648
     * }
     */
    public static int INT_LEAST32_MIN() {
        return INT_LEAST32_MIN;
    }
    private static final long INT_LEAST64_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_LEAST64_MIN() {
        return INT_LEAST64_MIN;
    }
    private static final int INT_LEAST8_MAX = (int)127L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST8_MAX 127
     * }
     */
    public static int INT_LEAST8_MAX() {
        return INT_LEAST8_MAX;
    }
    private static final int INT_LEAST16_MAX = (int)32767L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST16_MAX 32767
     * }
     */
    public static int INT_LEAST16_MAX() {
        return INT_LEAST16_MAX;
    }
    private static final int INT_LEAST32_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST32_MAX 2147483647
     * }
     */
    public static int INT_LEAST32_MAX() {
        return INT_LEAST32_MAX;
    }
    private static final long INT_LEAST64_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INT_LEAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_LEAST64_MAX() {
        return INT_LEAST64_MAX;
    }
    private static final int UINT_LEAST8_MAX = (int)255L;
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST8_MAX 255
     * }
     */
    public static int UINT_LEAST8_MAX() {
        return UINT_LEAST8_MAX;
    }
    private static final int UINT_LEAST16_MAX = (int)65535L;
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST16_MAX 65535
     * }
     */
    public static int UINT_LEAST16_MAX() {
        return UINT_LEAST16_MAX;
    }
    private static final int UINT_LEAST32_MAX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST32_MAX 4294967295
     * }
     */
    public static int UINT_LEAST32_MAX() {
        return UINT_LEAST32_MAX;
    }
    private static final long UINT_LEAST64_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST64_MAX -1
     * }
     */
    public static long UINT_LEAST64_MAX() {
        return UINT_LEAST64_MAX;
    }
    private static final int INT_FAST8_MIN = (int)-128L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST8_MIN -128
     * }
     */
    public static int INT_FAST8_MIN() {
        return INT_FAST8_MIN;
    }
    private static final int INT_FAST16_MIN = (int)-32768L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST16_MIN -32768
     * }
     */
    public static int INT_FAST16_MIN() {
        return INT_FAST16_MIN;
    }
    private static final int INT_FAST32_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST32_MIN -2147483648
     * }
     */
    public static int INT_FAST32_MIN() {
        return INT_FAST32_MIN;
    }
    private static final long INT_FAST64_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_FAST64_MIN() {
        return INT_FAST64_MIN;
    }
    private static final int INT_FAST8_MAX = (int)127L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST8_MAX 127
     * }
     */
    public static int INT_FAST8_MAX() {
        return INT_FAST8_MAX;
    }
    private static final int INT_FAST16_MAX = (int)32767L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST16_MAX 32767
     * }
     */
    public static int INT_FAST16_MAX() {
        return INT_FAST16_MAX;
    }
    private static final int INT_FAST32_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST32_MAX 2147483647
     * }
     */
    public static int INT_FAST32_MAX() {
        return INT_FAST32_MAX;
    }
    private static final long INT_FAST64_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INT_FAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_FAST64_MAX() {
        return INT_FAST64_MAX;
    }
    private static final int UINT_FAST8_MAX = (int)255L;
    /**
     * {@snippet lang=c :
     * #define UINT_FAST8_MAX 255
     * }
     */
    public static int UINT_FAST8_MAX() {
        return UINT_FAST8_MAX;
    }
    private static final int UINT_FAST16_MAX = (int)65535L;
    /**
     * {@snippet lang=c :
     * #define UINT_FAST16_MAX 65535
     * }
     */
    public static int UINT_FAST16_MAX() {
        return UINT_FAST16_MAX;
    }
    private static final int UINT_FAST32_MAX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define UINT_FAST32_MAX 4294967295
     * }
     */
    public static int UINT_FAST32_MAX() {
        return UINT_FAST32_MAX;
    }
    private static final long UINT_FAST64_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINT_FAST64_MAX -1
     * }
     */
    public static long UINT_FAST64_MAX() {
        return UINT_FAST64_MAX;
    }
    private static final long INTPTR_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INTPTR_MAX 9223372036854775807
     * }
     */
    public static long INTPTR_MAX() {
        return INTPTR_MAX;
    }
    private static final long INTPTR_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INTPTR_MIN -9223372036854775808
     * }
     */
    public static long INTPTR_MIN() {
        return INTPTR_MIN;
    }
    private static final long UINTPTR_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINTPTR_MAX -1
     * }
     */
    public static long UINTPTR_MAX() {
        return UINTPTR_MAX;
    }
    private static final long INTMAX_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define INTMAX_MAX 9223372036854775807
     * }
     */
    public static long INTMAX_MAX() {
        return INTMAX_MAX;
    }
    private static final long UINTMAX_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define UINTMAX_MAX -1
     * }
     */
    public static long UINTMAX_MAX() {
        return UINTMAX_MAX;
    }
    private static final long INTMAX_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define INTMAX_MIN -9223372036854775808
     * }
     */
    public static long INTMAX_MIN() {
        return INTMAX_MIN;
    }
    private static final long PTRDIFF_MIN = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define PTRDIFF_MIN -9223372036854775808
     * }
     */
    public static long PTRDIFF_MIN() {
        return PTRDIFF_MIN;
    }
    private static final long PTRDIFF_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define PTRDIFF_MAX 9223372036854775807
     * }
     */
    public static long PTRDIFF_MAX() {
        return PTRDIFF_MAX;
    }
    private static final long SIZE_MAX = -1L;
    /**
     * {@snippet lang=c :
     * #define SIZE_MAX -1
     * }
     */
    public static long SIZE_MAX() {
        return SIZE_MAX;
    }
    private static final long RSIZE_MAX = 9223372036854775807L;
    /**
     * {@snippet lang=c :
     * #define RSIZE_MAX 9223372036854775807
     * }
     */
    public static long RSIZE_MAX() {
        return RSIZE_MAX;
    }
    private static final int WCHAR_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define WCHAR_MAX 2147483647
     * }
     */
    public static int WCHAR_MAX() {
        return WCHAR_MAX;
    }
    private static final int WCHAR_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define WCHAR_MIN -2147483648
     * }
     */
    public static int WCHAR_MIN() {
        return WCHAR_MIN;
    }
    private static final int WINT_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define WINT_MIN -2147483648
     * }
     */
    public static int WINT_MIN() {
        return WINT_MIN;
    }
    private static final int WINT_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define WINT_MAX 2147483647
     * }
     */
    public static int WINT_MAX() {
        return WINT_MAX;
    }
    private static final int SIG_ATOMIC_MIN = (int)-2147483648L;
    /**
     * {@snippet lang=c :
     * #define SIG_ATOMIC_MIN -2147483648
     * }
     */
    public static int SIG_ATOMIC_MIN() {
        return SIG_ATOMIC_MIN;
    }
    private static final int SIG_ATOMIC_MAX = (int)2147483647L;
    /**
     * {@snippet lang=c :
     * #define SIG_ATOMIC_MAX 2147483647
     * }
     */
    public static int SIG_ATOMIC_MAX() {
        return SIG_ATOMIC_MAX;
    }
}

