// Generated by jextract

package com.jakewharton.mosaic.tty;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct MosaicTestTtyInitResult {
 *     MosaicTestTty *testTty;
 *     uint32_t error;
 *     bool already_bound;
 * }
 * }
 */
public class MosaicTestTtyInitResult {

    MosaicTestTtyInitResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Libmosaic.C_POINTER.withName("testTty"),
        Libmosaic.C_INT.withName("error"),
        Libmosaic.C_BOOL.withName("already_bound"),
        MemoryLayout.paddingLayout(3)
    ).withName("MosaicTestTtyInitResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout testTty$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("testTty"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * MosaicTestTty *testTty
     * }
     */
    public static final AddressLayout testTty$layout() {
        return testTty$LAYOUT;
    }

    private static final long testTty$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * MosaicTestTty *testTty
     * }
     */
    public static final long testTty$offset() {
        return testTty$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * MosaicTestTty *testTty
     * }
     */
    public static MemorySegment testTty(MemorySegment struct) {
        return struct.get(testTty$LAYOUT, testTty$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * MosaicTestTty *testTty
     * }
     */
    public static void testTty(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(testTty$LAYOUT, testTty$OFFSET, fieldValue);
    }

    private static final OfInt error$LAYOUT = (OfInt)$LAYOUT.select(groupElement("error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t error
     * }
     */
    public static final OfInt error$layout() {
        return error$LAYOUT;
    }

    private static final long error$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t error
     * }
     */
    public static final long error$offset() {
        return error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t error
     * }
     */
    public static int error(MemorySegment struct) {
        return struct.get(error$LAYOUT, error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t error
     * }
     */
    public static void error(MemorySegment struct, int fieldValue) {
        struct.set(error$LAYOUT, error$OFFSET, fieldValue);
    }

    private static final OfBoolean already_bound$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("already_bound"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool already_bound
     * }
     */
    public static final OfBoolean already_bound$layout() {
        return already_bound$LAYOUT;
    }

    private static final long already_bound$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool already_bound
     * }
     */
    public static final long already_bound$offset() {
        return already_bound$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool already_bound
     * }
     */
    public static boolean already_bound(MemorySegment struct) {
        return struct.get(already_bound$LAYOUT, already_bound$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool already_bound
     * }
     */
    public static void already_bound(MemorySegment struct, boolean fieldValue) {
        struct.set(already_bound$LAYOUT, already_bound$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

