// Generated by jextract

package com.jakewharton.mosaic.tty;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (MosaicTtyCallbackOnFocus)(void *, bool)
 * }
 */
public class MosaicTtyCallbackOnFocus {

    MosaicTtyCallbackOnFocus() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment opaque, boolean focused);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        Libmosaic.C_POINTER,
        Libmosaic.C_BOOL
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Libmosaic.upcallHandle(MosaicTtyCallbackOnFocus.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(MosaicTtyCallbackOnFocus.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr,MemorySegment opaque, boolean focused) {
        try {
             DOWN$MH.invokeExact(funcPtr, opaque, focused);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

