// Generated by jextract

package com.jakewharton.mosaic.tty;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct MosaicTtyCallback {
 *     void *opaque;
 *     MosaicTtyCallbackOnFocus *onFocus;
 *     MosaicTtyCallbackOnKey *onKey;
 *     MosaicTtyCallbackOnMouse *onMouse;
 *     MosaicTtyCallbackOnResize *onResize;
 * }
 * }
 */
public class MosaicTtyCallback {

    MosaicTtyCallback() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Libmosaic.C_POINTER.withName("opaque"),
        Libmosaic.C_POINTER.withName("onFocus"),
        Libmosaic.C_POINTER.withName("onKey"),
        Libmosaic.C_POINTER.withName("onMouse"),
        Libmosaic.C_POINTER.withName("onResize")
    ).withName("MosaicTtyCallback");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout opaque$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("opaque"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *opaque
     * }
     */
    public static final AddressLayout opaque$layout() {
        return opaque$LAYOUT;
    }

    private static final long opaque$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *opaque
     * }
     */
    public static final long opaque$offset() {
        return opaque$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *opaque
     * }
     */
    public static MemorySegment opaque(MemorySegment struct) {
        return struct.get(opaque$LAYOUT, opaque$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *opaque
     * }
     */
    public static void opaque(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(opaque$LAYOUT, opaque$OFFSET, fieldValue);
    }

    private static final AddressLayout onFocus$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("onFocus"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnFocus *onFocus
     * }
     */
    public static final AddressLayout onFocus$layout() {
        return onFocus$LAYOUT;
    }

    private static final long onFocus$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnFocus *onFocus
     * }
     */
    public static final long onFocus$offset() {
        return onFocus$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnFocus *onFocus
     * }
     */
    public static MemorySegment onFocus(MemorySegment struct) {
        return struct.get(onFocus$LAYOUT, onFocus$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnFocus *onFocus
     * }
     */
    public static void onFocus(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(onFocus$LAYOUT, onFocus$OFFSET, fieldValue);
    }

    private static final AddressLayout onKey$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("onKey"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnKey *onKey
     * }
     */
    public static final AddressLayout onKey$layout() {
        return onKey$LAYOUT;
    }

    private static final long onKey$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnKey *onKey
     * }
     */
    public static final long onKey$offset() {
        return onKey$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnKey *onKey
     * }
     */
    public static MemorySegment onKey(MemorySegment struct) {
        return struct.get(onKey$LAYOUT, onKey$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnKey *onKey
     * }
     */
    public static void onKey(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(onKey$LAYOUT, onKey$OFFSET, fieldValue);
    }

    private static final AddressLayout onMouse$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("onMouse"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnMouse *onMouse
     * }
     */
    public static final AddressLayout onMouse$layout() {
        return onMouse$LAYOUT;
    }

    private static final long onMouse$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnMouse *onMouse
     * }
     */
    public static final long onMouse$offset() {
        return onMouse$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnMouse *onMouse
     * }
     */
    public static MemorySegment onMouse(MemorySegment struct) {
        return struct.get(onMouse$LAYOUT, onMouse$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnMouse *onMouse
     * }
     */
    public static void onMouse(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(onMouse$LAYOUT, onMouse$OFFSET, fieldValue);
    }

    private static final AddressLayout onResize$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("onResize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnResize *onResize
     * }
     */
    public static final AddressLayout onResize$layout() {
        return onResize$LAYOUT;
    }

    private static final long onResize$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnResize *onResize
     * }
     */
    public static final long onResize$offset() {
        return onResize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnResize *onResize
     * }
     */
    public static MemorySegment onResize(MemorySegment struct) {
        return struct.get(onResize$LAYOUT, onResize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * MosaicTtyCallbackOnResize *onResize
     * }
     */
    public static void onResize(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(onResize$LAYOUT, onResize$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

