// Generated by jextract

package com.jakewharton.mosaic.tty;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct MosaicTtyInitResult {
 *     MosaicTty *tty;
 *     uint32_t error;
 *     bool no_tty;
 *     bool already_bound;
 * }
 * }
 */
public class MosaicTtyInitResult {

    MosaicTtyInitResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Libmosaic.C_POINTER.withName("tty"),
        Libmosaic.C_INT.withName("error"),
        Libmosaic.C_BOOL.withName("no_tty"),
        Libmosaic.C_BOOL.withName("already_bound"),
        MemoryLayout.paddingLayout(2)
    ).withName("MosaicTtyInitResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout tty$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("tty"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * MosaicTty *tty
     * }
     */
    public static final AddressLayout tty$layout() {
        return tty$LAYOUT;
    }

    private static final long tty$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * MosaicTty *tty
     * }
     */
    public static final long tty$offset() {
        return tty$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * MosaicTty *tty
     * }
     */
    public static MemorySegment tty(MemorySegment struct) {
        return struct.get(tty$LAYOUT, tty$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * MosaicTty *tty
     * }
     */
    public static void tty(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(tty$LAYOUT, tty$OFFSET, fieldValue);
    }

    private static final OfInt error$LAYOUT = (OfInt)$LAYOUT.select(groupElement("error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t error
     * }
     */
    public static final OfInt error$layout() {
        return error$LAYOUT;
    }

    private static final long error$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t error
     * }
     */
    public static final long error$offset() {
        return error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t error
     * }
     */
    public static int error(MemorySegment struct) {
        return struct.get(error$LAYOUT, error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t error
     * }
     */
    public static void error(MemorySegment struct, int fieldValue) {
        struct.set(error$LAYOUT, error$OFFSET, fieldValue);
    }

    private static final OfBoolean no_tty$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("no_tty"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool no_tty
     * }
     */
    public static final OfBoolean no_tty$layout() {
        return no_tty$LAYOUT;
    }

    private static final long no_tty$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool no_tty
     * }
     */
    public static final long no_tty$offset() {
        return no_tty$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool no_tty
     * }
     */
    public static boolean no_tty(MemorySegment struct) {
        return struct.get(no_tty$LAYOUT, no_tty$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool no_tty
     * }
     */
    public static void no_tty(MemorySegment struct, boolean fieldValue) {
        struct.set(no_tty$LAYOUT, no_tty$OFFSET, fieldValue);
    }

    private static final OfBoolean already_bound$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("already_bound"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool already_bound
     * }
     */
    public static final OfBoolean already_bound$layout() {
        return already_bound$LAYOUT;
    }

    private static final long already_bound$OFFSET = 13;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool already_bound
     * }
     */
    public static final long already_bound$offset() {
        return already_bound$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool already_bound
     * }
     */
    public static boolean already_bound(MemorySegment struct) {
        return struct.get(already_bound$LAYOUT, already_bound$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool already_bound
     * }
     */
    public static void already_bound(MemorySegment struct, boolean fieldValue) {
        struct.set(already_bound$LAYOUT, already_bound$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

