// Generated by jextract

package com.jakewharton.mosaic.tty;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct MosaicTtyTerminalSizeResult {
 *     int columns;
 *     int rows;
 *     int width;
 *     int height;
 *     uint32_t error;
 * }
 * }
 */
public class MosaicTtyTerminalSizeResult {

    MosaicTtyTerminalSizeResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Libmosaic.C_INT.withName("columns"),
        Libmosaic.C_INT.withName("rows"),
        Libmosaic.C_INT.withName("width"),
        Libmosaic.C_INT.withName("height"),
        Libmosaic.C_INT.withName("error")
    ).withName("MosaicTtyTerminalSizeResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt columns$LAYOUT = (OfInt)$LAYOUT.select(groupElement("columns"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int columns
     * }
     */
    public static final OfInt columns$layout() {
        return columns$LAYOUT;
    }

    private static final long columns$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int columns
     * }
     */
    public static final long columns$offset() {
        return columns$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int columns
     * }
     */
    public static int columns(MemorySegment struct) {
        return struct.get(columns$LAYOUT, columns$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int columns
     * }
     */
    public static void columns(MemorySegment struct, int fieldValue) {
        struct.set(columns$LAYOUT, columns$OFFSET, fieldValue);
    }

    private static final OfInt rows$LAYOUT = (OfInt)$LAYOUT.select(groupElement("rows"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int rows
     * }
     */
    public static final OfInt rows$layout() {
        return rows$LAYOUT;
    }

    private static final long rows$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int rows
     * }
     */
    public static final long rows$offset() {
        return rows$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int rows
     * }
     */
    public static int rows(MemorySegment struct) {
        return struct.get(rows$LAYOUT, rows$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int rows
     * }
     */
    public static void rows(MemorySegment struct, int fieldValue) {
        struct.set(rows$LAYOUT, rows$OFFSET, fieldValue);
    }

    private static final OfInt width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static final OfInt width$layout() {
        return width$LAYOUT;
    }

    private static final long width$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static final long width$offset() {
        return width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static int width(MemorySegment struct) {
        return struct.get(width$LAYOUT, width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int width
     * }
     */
    public static void width(MemorySegment struct, int fieldValue) {
        struct.set(width$LAYOUT, width$OFFSET, fieldValue);
    }

    private static final OfInt height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static final OfInt height$layout() {
        return height$LAYOUT;
    }

    private static final long height$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static final long height$offset() {
        return height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static int height(MemorySegment struct) {
        return struct.get(height$LAYOUT, height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int height
     * }
     */
    public static void height(MemorySegment struct, int fieldValue) {
        struct.set(height$LAYOUT, height$OFFSET, fieldValue);
    }

    private static final OfInt error$LAYOUT = (OfInt)$LAYOUT.select(groupElement("error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t error
     * }
     */
    public static final OfInt error$layout() {
        return error$LAYOUT;
    }

    private static final long error$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t error
     * }
     */
    public static final long error$offset() {
        return error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t error
     * }
     */
    public static int error(MemorySegment struct) {
        return struct.get(error$LAYOUT, error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t error
     * }
     */
    public static void error(MemorySegment struct, int fieldValue) {
        struct.set(error$LAYOUT, error$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

