name: build

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'trunk'
    tags-ignore:
      - '**'

jobs:
  zig:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: zig build -p src/jvmMain/resources/jni
        working-directory: mosaic-terminal
      - uses: actions/upload-artifact@v4
        with:
          name: jni
          path: mosaic-terminal/src/jvmMain/resources/jni
          if-no-files-found: error

  build:
    needs:
      - zig
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: jni
          path: mosaic-terminal/src/jvmMain/resources
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 23
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-home-cache-cleanup: true

      - run: ./gradlew build :samples:jest:run
        env:
          MOSAIC_RAW_MODE: false

  publish:
    runs-on: macos-latest
    if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'JakeWharton/mosaic' }}
    needs:
      - build

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: jni
          path: mosaic-terminal/src/jvmMain/resources
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 23
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-home-cache-cleanup: true

      - run: ./gradlew publish :mosaic-runtime:dokkaHtml
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

      - name: Deploy docs to website
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: site
          FOLDER: mosaic-runtime/build/dokka/html/
          TARGET_FOLDER: docs/latest/
          CLEAN: true
