name: build

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'trunk'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-home-cache-cleanup: true

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: zig build -p src/jvmMain/resources/jni
        working-directory: mosaic-terminal

      - run: ./gradlew build :samples:jest:run :mosaic-runtime:dokkaHtml
        env:
          MOSAIC_RAW_MODE: false

      - run: ./gradlew publish
        if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'JakeWharton/mosaic' }}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

      - name: Deploy docs to website
        if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'JakeWharton/mosaic' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: site
          FOLDER: mosaic-runtime/build/dokka/html/
          TARGET_FOLDER: docs/latest/
          CLEAN: true
